---
- hosts: localhost
  remote_user: root

  vars:

    database_driver: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_DRIVER')|default('pdo_sqlite', true) }}"
    database_driver_class: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_DRIVER_CLASS')|default('~', true) }}"
    database_host: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_HOST')|default('127.0.0.1', true) }}"
    database_name: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_NAME')|default('symfony', true) }}"
    database_password: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_PASSWORD')|default('~', true) }}"
    database_port: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_PORT')|default('~', true) }}"
    database_root_password_mariadb: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    database_root_user_postgres: "{{ lookup('env', 'POSTGRES_USER') }}"
    database_root_password_postgres: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    database_user: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_USER')|default('root', true) }}"
    database_charset: "{{ lookup('env', 'SYMFONY__ENV__DATABASE_CHARSET')|default('utf8', true) }}"
    populate_database: "{{ lookup('env', 'POPULATE_DATABASE')|default(True, true) }}"
    locale: "{{ lookup('env', 'SYMFONY__ENV__LOCALE')|default('en', true) }}"
    secret: "{{ lookup('env', 'SYMFONY__ENV__SECRET')|default('C3C8vfSm1zkG84afyDLSyyXxteXA4', true) }}"
    mailer_host: "{{ lookup('env', 'SYMFONY__ENV__MAILER_HOST')|default('127.0.0.1', true) }}"
    mailer_user: "{{ lookup('env', 'SYMFONY__ENV__MAILER_USER')|default('~', true) }}"
    mailer_password: "{{ lookup('env', 'SYMFONY__ENV__MAILER_PASSWORD')|default('~', true) }}"
    from_email: "{{ lookup('env', 'SYMFONY__ENV__FROM_EMAIL')|default('wallabag@example.com', true) }}"
    registration: "{{ lookup('env', 'SYMFONY__ENV__FOSUSER_REGISTRATION')|default('true', true) }}"
    registration_mail_confirmation: "{{ lookup('env', 'SYMFONY__ENV__FOSUSER_CONFIRMATION')|default('true', true) }}"
    domain_name: "{{ lookup('env', 'SYMFONY__ENV__DOMAIN_NAME')|default('https://your-wallabag-url-instance.com', true) }}"
    rss_limit: "{{ lookup('env', 'SYMFONY__ENV__RSS_LIMIT')|default('50', true) }}"

  tasks:

    - name: Create application and data directories
      file:
        path={{ item }}
        state=directory
      with_items:
        - /var/www/wallabag/app
        - /var/www/wallabag/app/config
        - /var/www/wallabag/data
        - /var/www/wallabag/data/assets
        - /var/www/wallabag/data/db
      notify: Chown Dir
      tags:
        - firstrun

    - name: Write variables to parameters.yml
      template:
        src=templates/parameters.yml.j2
        dest=/var/www/wallabag/app/config/parameters.yml

    - stat:
        path=/var/www/wallabag/data/db/wallabag.sqlite
      register: wallabag_sqlite_db
      when: database_driver == 'pdo_sqlite'

    - name: Run install when sqlite db is not present
      debug:
        msg='notify installation script if sqlite db does not exist'
      changed_when: true
      notify: Run Install
      when: wallabag_sqlite_db.stat.exists == False

    - name: Find all files under cache directory
      find:
        paths: /var/www/wallabag/var/cache/
        patterns: "*.*"
      register: wallabag_cache_glob_list

    - name: Remove all files under cache directory
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ wallabag_cache_glob_list.files }}"

    - name: Run composer install
      shell: SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
      args:
        chdir: /var/www/wallabag
      notify: Chown Dir

  handlers:

    - name: Run Install
      shell: php bin/console wallabag:install --env=prod -n
      args:
        chdir: /var/www/wallabag
      notify: Chown Dir

    - name: Chown Dir
      file:
        path=/var/www/wallabag
        recurse=yes
        owner=nobody
        group=nobody
